"use client";

import { Modal } from "@/components/ui/Modal";
import { useMindWeather } from "@/hooks/useMindWeather";
import type { ViewId } from "@/lib/types";
import type { AuthAccount } from "@/services/authService";
import { authService } from "@/services/authService";
import { disableGoogleAutoSelect } from "@/services/googleIdentityService";
import { Accessibility, Bell, Check, Cloud, Database, Download, Eye, KeyRound, Laptop, LockKeyhole, LogOut, Moon, Palette, RotateCcw, ShieldCheck, Sun, Trash2, UserRound } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

const tabs = [{ id: "account", label: "Account", icon: UserRound }, { id: "appearance", label: "Appearance", icon: Palette }, { id: "accessibility", label: "Accessibility", icon: Accessibility }, { id: "notifications", label: "Notifications", icon: Bell }, { id: "privacy", label: "Privacy", icon: ShieldCheck }, { id: "data", label: "Data", icon: Database }];

export function SettingsView({}: { navigate?(view: ViewId): void }) {
  const router = useRouter();
  const { state, updatePreferences, updateProfile, downloadData, resetDemo, deleteData } = useMindWeather();
  const [tab, setTab] = useState("account");
  const [confirm, setConfirm] = useState<"delete" | "reset" | null>(null);
  const [account, setAccount] = useState<AuthAccount | null>(null);
  useEffect(() => {
    const frame = window.requestAnimationFrame(() => setAccount(authService.current()));
    return () => window.cancelAnimationFrame(frame);
  }, []);
  const signOut = () => { authService.logout(); disableGoogleAutoSelect(); setAccount(null); router.push("/"); };
  return <div className="settings-page"><header className="view-heading"><span className="view-heading__eyebrow">Settings & privacy</span><h1>Make the station yours.</h1><p>Every recommendation is built from the information visible here.</p></header><div className="settings-layout"><aside className="settings-nav panel">{tabs.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => setTab(id)} className={tab === id ? "active" : ""}><Icon />{label}</button>)}</aside><section className="settings-content panel">
      {tab === "account" && <SettingsSection title="Account & local profile" detail="Your account and study data stay on this device."><div className="profile-edit"><span className="profile-edit__avatar">{state.profile.initials}</span><label className="form-field"><span>Name</span><input className="input" value={state.profile.name} onChange={(event) => updateProfile({ name: event.target.value, initials: event.target.value.split(" ").map((part) => part[0]).join("").slice(0,2).toUpperCase() })} /></label><label className="form-field"><span>Study field</span><input className="input" value={state.profile.field} onChange={(event) => updateProfile({ field: event.target.value })} /></label><label className="form-field"><span>Email</span><input className="input" type="email" value={state.profile.email} onChange={(event) => updateProfile({ email: event.target.value })} /></label></div>{account ? <SettingRow icon={account.providers.includes("google") ? ShieldCheck : KeyRound} title={`Signed in as ${account.email}`} detail={`Using ${account.providers.map((provider) => provider === "google" ? "Google" : "a local password").join(" and ")}. Signing out does not delete study data.`}><button className="button button--ghost button--small" onClick={signOut}><LogOut /> Sign out</button></SettingRow> : <SettingRow icon={KeyRound} title="Sign in on this device" detail="Use Google or create a local password profile."><Link href="/login" className="button button--ghost button--small">Sign in</Link></SettingRow>}</SettingsSection>}
      {tab === "appearance" && <SettingsSection title="Atmosphere" detail="Change the station’s lighting without changing its information."><div className="theme-grid">{([{ id: "atmospheric", label: "Atmospheric", icon: Cloud }, { id: "midnight", label: "Midnight", icon: Moon }, { id: "cloudlight", label: "Cloudlight", icon: Sun }, { id: "contrast", label: "High Contrast", icon: Eye }] as const).map(({ id, label, icon: Icon }) => <button key={id} className={state.preferences.theme === id ? `theme-swatch theme-swatch--${id} active` : `theme-swatch theme-swatch--${id}`} onClick={() => updatePreferences({ theme: id })}><span><Icon /></span><strong>{label}</strong>{state.preferences.theme === id && <Check />}</button>)}</div></SettingsSection>}
      {tab === "accessibility" && <SettingsSection title="Accessibility" detail="Readable, calm, and operable is the baseline."><ToggleRow icon={Moon} title="Reduce motion" detail="Turns off weather drift, transitions, and celebratory motion." value={state.preferences.reduceMotion} onChange={(value) => updatePreferences({ reduceMotion: value })} /><ToggleRow icon={Eye} title="Increase contrast" detail="Strengthens borders, text, and status differentiation." value={state.preferences.highContrast} onChange={(value) => updatePreferences({ highContrast: value })} /><ToggleRow icon={Accessibility} title="Larger text" detail="Increases body and control text without breaking layout." value={state.preferences.largeText} onChange={(value) => updatePreferences({ largeText: value })} /><SettingRow icon={Laptop} title="Keyboard navigation" detail="All core flows support visible focus and keyboard operation."><span className="pill">Always on</span></SettingRow></SettingsSection>}
      {tab === "notifications" && <SettingsSection title="Notifications" detail="Compassionate signals only. Nothing that scolds."><ToggleRow icon={Bell} title="Helpful reminders" detail="Deadline nudges, resurfaced notes, and useful patterns." value={state.preferences.notifications} onChange={(value) => updatePreferences({ notifications: value })} /><ToggleRow icon={RotateCcw} title="Optional streaks" detail="Streaks are hidden by default and never affect progress." value={state.preferences.streaks} onChange={(value) => updatePreferences({ streaks: value })} /><div className="notification-example"><span>EXAMPLE</span><p>“Your calculus deadline is getting closer. Want help shrinking the next step?”</p></div></SettingsSection>}
      {tab === "privacy" && <SettingsSection title="Privacy centre" detail="Clear answers about what the station knows."><div className="privacy-list"><article><span><Database /></span><div><strong>What is stored</strong><p>Tasks, study sessions, check-ins, notes, mistakes, journal entries, settings, and the local profile.</p></div></article><article><span><Eye /></span><div><strong>What shapes recommendations</strong><p>Self-reported weather, completion history, timing, session ratings, deadlines, and learning preferences.</p></div></article><article><span><LockKeyhole /></span><div><strong>What stays private</strong><p>Everything. This build keeps all study behaviour in your browser on this device.</p></div></article></div><div className="privacy-promise"><ShieldCheck /><span><strong>Your study behaviour is not a product.</strong><small>MindWeather never sells, exposes, or silently uploads it.</small></span></div></SettingsSection>}
      {tab === "data" && <SettingsSection title="Your data" detail="Portable when you want it. Removable when you don’t."><SettingRow icon={Download} title="Download my data" detail="Export every locally stored MindWeather record as readable JSON."><button className="button button--ghost button--small" onClick={downloadData}>Download</button></SettingRow><SettingRow icon={RotateCcw} title="Restore the demo learner" detail="Replace current records with the polished Simone demo profile."><button className="button button--ghost button--small" onClick={() => setConfirm("reset")}>Restore</button></SettingRow><SettingRow icon={Trash2} title="Delete my data" detail="Remove tasks, study history, notes, mistakes, and preferences from this device."><button className="button button--danger button--small" onClick={() => setConfirm("delete")}>Delete</button></SettingRow></SettingsSection>}
    </section></div><Modal open={!!confirm} onClose={() => setConfirm(null)} title={confirm === "delete" ? "Delete local study data?" : "Restore the demo learner?"} eyebrow="A deliberate choice"><div className="confirm-action"><p>{confirm === "delete" ? "This removes the current MindWeather records from this browser. Download a copy first if you may want them later." : "This replaces the current local records with the original lively demo data."}</p><div><button className="button button--ghost" onClick={() => setConfirm(null)}>Keep things as they are</button><button className={confirm === "delete" ? "button button--danger" : "button button--peach"} onClick={() => { if (confirm === "delete") deleteData(); else resetDemo(); setConfirm(null); }}>{confirm === "delete" ? <Trash2 /> : <RotateCcw />}{confirm === "delete" ? "Delete local data" : "Restore demo"}</button></div></div></Modal></div>;
}

function SettingsSection({ title, detail, children }: { title: string; detail: string; children: React.ReactNode }) { return <div className="settings-section"><header><h2>{title}</h2><p>{detail}</p></header>{children}</div>; }
function SettingRow({ icon: Icon, title, detail, children }: { icon: typeof UserRound; title: string; detail: string; children: React.ReactNode }) { return <div className="setting-row"><span><Icon /></span><div><strong>{title}</strong><small>{detail}</small></div>{children}</div>; }
function ToggleRow({ icon, title, detail, value, onChange }: { icon: typeof UserRound; title: string; detail: string; value: boolean; onChange(value: boolean): void }) { return <SettingRow icon={icon} title={title} detail={detail}><button role="switch" aria-checked={value} onClick={() => onChange(!value)} className={value ? "switch active" : "switch"}><i /></button></SettingRow>; }
