import type { AppState } from "./types";
import { seedDemoRecords } from "./seed-data";

const day = (offset: number, hour = 12, minute = 0) => {
  const date = new Date();
  date.setDate(date.getDate() + offset);
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
};

export const demoState: AppState = {
  version: 2,
  profile: {
    id: "profile-simone",
    name: "Simoné",
    email: "simone@mindweather.local",
    initials: "SG",
    field: "Design Thinking & Experience Learning",
    focusWindow: "Afternoon",
    learningMethods: ["Visual", "Practising", "Explaining"],
    obstacles: ["Getting started", "Overwhelm", "Understanding difficult concepts"],
    onboarded: true,
  },
  preferences: {
    theme: "atmospheric",
    supportMode: "flexible",
    reduceMotion: false,
    largeText: false,
    highContrast: false,
    notifications: true,
    streaks: false,
    focusLength: 25,
    breakLength: 5,
    overwhelmAction: "one-task",
  },
  subjects: [
    { id: "frontend", name: "Frontend Development", color: "#8fe7dd", icon: "FE" },
    { id: "ux", name: "UX Design", color: "#ffb58b", icon: "UX" },
    { id: "javascript", name: "JavaScript", color: "#d6c377", icon: "JS" },
    { id: "research", name: "Research", color: "#b4a0ff", icon: "R" },
    { id: "thinking", name: "Design Thinking Sprint", color: "#f2a2cb", icon: "DT" },
    { id: "experience", name: "Experience Learning", color: "#f6c88f", icon: "XL" },
    { id: "career", name: "Setting Up for Success", color: "#fff0b9", icon: "CR" },
    { id: "sap", name: "SAP Integration Development", color: "#9fc1ff", icon: "SAP" },
  ],
  tasks: [
    {
      id: "classroom-dt-define",
      title: "Complete Phase 2: Define evidence pack",
      subjectId: "thinking",
      description: "Finish the findings, POV statement, problem statement, How Might We questions, prioritisation and readable BPMN model.",
      deadline: "2026-08-14T21:59:00.000Z",
      estimatedMinutes: 75,
      actualMinutes: 35,
      priority: 3,
      difficulty: 4,
      energy: 4,
      focus: 4,
      type: "Write",
      status: "working",
      notes: "Google Classroom has no separate due date for this phase. It is planned against the 14 August final sprint hand-in.",
      subtasks: [
        { id: "define-findings", title: "Complete findings and theme tables", done: true },
        { id: "define-bpmn", title: "Check BPMN labels and spacing", done: true },
        { id: "define-sources", title: "Check citations and reference links", done: false },
        { id: "define-upload", title: "Upload an individual copy of the evidence", done: false },
      ],
      conceptIds: ["affinity-mapping", "point-of-view", "bpmn"],
      createdAt: "2026-07-28T08:00:00.000Z",
    },
    {
      id: "classroom-linkedin",
      title: "Networking via LinkedIn",
      subjectId: "career",
      description: "Complete the LinkedIn networking assignment for the Setting Up for Success class.",
      deadline: "2026-08-10T21:59:00.000Z",
      estimatedMinutes: 35,
      actualMinutes: 0,
      priority: 3,
      difficulty: 2,
      energy: 2,
      focus: 2,
      type: "Write",
      status: "planned",
      notes: "Google Classroom deadline: Monday, 10 August 2026 at 11:59 PM.",
      subtasks: [
        { id: "linkedin-brief", title: "Read the assignment brief", done: false },
        { id: "linkedin-proof", title: "Prepare the required evidence", done: false },
      ],
      conceptIds: [],
      createdAt: "2026-08-03T08:00:00.000Z",
    },
    {
      id: "classroom-logbook",
      title: "Update Design Thinking Sprint logbook",
      subjectId: "thinking",
      description: "Record sprint activities, assessments, self-directed learning, coaching, collaboration and Portfolio of Evidence links.",
      deadline: "2026-08-14T21:59:00.000Z",
      estimatedMinutes: 50,
      actualMinutes: 10,
      priority: 3,
      difficulty: 3,
      energy: 2,
      focus: 3,
      type: "Write",
      status: "working",
      notes: "Google Classroom deadline: Friday, 14 August 2026. Record only work personally completed and check the required signatures.",
      subtasks: [
        { id: "logbook-days", title: "Bring every sprint day up to date", done: false },
        { id: "logbook-hours", title: "Check learning and notional hours", done: false },
        { id: "logbook-signatures", title: "Check required signatures", done: false },
      ],
      conceptIds: [],
      createdAt: "2026-07-27T08:00:00.000Z",
    },
    {
      id: "classroom-final-submission",
      title: "Final Sprint submission and declaration",
      subjectId: "thinking",
      description: "Submit the assessment practices review, signed Declaration of Authenticity and fully completed logbook.",
      deadline: "2026-08-14T21:59:00.000Z",
      estimatedMinutes: 45,
      actualMinutes: 0,
      priority: 3,
      difficulty: 3,
      energy: 2,
      focus: 3,
      type: "Other",
      status: "planned",
      notes: "Google Classroom deadline: Friday, 14 August 2026. Complete the review after the final presentation and check that every attachment opens.",
      subtasks: [
        { id: "final-review", title: "Complete the assessor practices review", done: false },
        { id: "final-declaration", title: "Sign the Declaration of Authenticity", done: false },
        { id: "final-logbook", title: "Attach the completed logbook", done: false },
      ],
      conceptIds: [],
      createdAt: "2026-07-31T08:00:00.000Z",
    },
    {
      id: "classroom-seta-feedback",
      title: "MICT SETA accreditation feedback",
      subjectId: "thinking",
      description: "Give honest feedback on the accreditation journey, the assessment explanation, required evidence and anything still unclear.",
      deadline: "2026-08-14T21:59:00.000Z",
      estimatedMinutes: 20,
      actualMinutes: 0,
      priority: 2,
      difficulty: 2,
      energy: 2,
      focus: 2,
      type: "Write",
      status: "planned",
      notes: "Google Classroom deadline: Friday, 14 August 2026.",
      subtasks: [{ id: "seta-honest", title: "Answer from my own experience", done: false }],
      conceptIds: [],
      createdAt: "2026-07-31T08:00:00.000Z",
    },
    {
      id: "classroom-soft-skills-confidence",
      title: "Soft Skills: Self-Confidence and Self-Control",
      subjectId: "career",
      description: "Complete module 6.2 in the Setting Up for Success class.",
      deadline: "2026-08-17T21:59:00.000Z",
      estimatedMinutes: 45,
      actualMinutes: 0,
      priority: 2,
      difficulty: 2,
      energy: 2,
      focus: 2,
      type: "Read",
      status: "planned",
      notes: "Google Classroom deadline: Monday, 17 August 2026.",
      subtasks: [],
      conceptIds: [],
      createdAt: "2026-07-27T08:00:00.000Z",
    },
    {
      id: "classroom-soft-skills-communication",
      title: "Soft Skills: Communication",
      subjectId: "career",
      description: "Complete module 6.3 in the Setting Up for Success class.",
      deadline: "2026-08-17T21:59:00.000Z",
      estimatedMinutes: 45,
      actualMinutes: 0,
      priority: 2,
      difficulty: 2,
      energy: 2,
      focus: 2,
      type: "Read",
      status: "planned",
      notes: "Google Classroom deadline: Monday, 17 August 2026.",
      subtasks: [],
      conceptIds: [],
      createdAt: "2026-07-27T08:00:00.000Z",
    },
    {
      id: "classroom-baseline",
      title: "Work readiness: Baseline Assessments",
      subjectId: "career",
      description: "Complete the work-readiness baseline assessment in the Setting Up for Success class.",
      deadline: "2026-08-17T21:59:00.000Z",
      estimatedMinutes: 40,
      actualMinutes: 0,
      priority: 2,
      difficulty: 2,
      energy: 2,
      focus: 3,
      type: "Other",
      status: "planned",
      notes: "Google Classroom deadline: Monday, 17 August 2026.",
      subtasks: [],
      conceptIds: [],
      createdAt: "2026-07-27T08:00:00.000Z",
    },
    {
      id: "classroom-sap-overdue",
      title: "SAP Certified Associate: Integration Developer",
      subjectId: "sap",
      description: "Review the older Course 4 assignment and confirm what still needs to be completed or resubmitted.",
      deadline: "2026-06-19T21:59:00.000Z",
      estimatedMinutes: 60,
      actualMinutes: 0,
      priority: 3,
      difficulty: 4,
      energy: 4,
      focus: 4,
      type: "Practise",
      status: "blocked",
      notes: "Google Classroom lists Friday, 19 June 2026. It is kept as an overdue item until its status is confirmed.",
      subtasks: [{ id: "sap-confirm", title: "Confirm whether the assignment is still required", done: false }],
      conceptIds: [],
      createdAt: "2026-06-01T08:00:00.000Z",
    },
  ],
  weatherCheckins: [
    { id: "w1", weather: "breezy", energy: 3, focus: 3, stress: 2, motivation: 4, createdAt: day(-6, 10, 10) },
    { id: "w2", weather: "clear", energy: 4, focus: 5, stress: 2, motivation: 4, createdAt: day(-5, 15, 10) },
    { id: "w3", weather: "battery", energy: 2, focus: 3, stress: 3, motivation: 2, createdAt: day(-4, 19, 5) },
    { id: "w4", weather: "clear", energy: 4, focus: 4, stress: 1, motivation: 4, createdAt: day(-3, 15, 20) },
    { id: "w5", weather: "foggy", energy: 3, focus: 2, stress: 2, motivation: 3, createdAt: day(-2, 11, 40) },
    { id: "w6", weather: "breezy", energy: 3, focus: 3, stress: 3, motivation: 3, createdAt: day(-1, 16, 0) },
  ],
  sessions: [
    { id: "s1", taskId: "classroom-dt-define", subjectId: "thinking", minutes: 25, completedMinutes: 25, focusQuality: 4, felt: "Okay", method: "practice", completedAt: day(-5, 15, 45) },
    { id: "s2", taskId: "classroom-logbook", subjectId: "thinking", minutes: 15, completedMinutes: 12, focusQuality: 3, felt: "Hard", method: "explaining", completedAt: day(-4, 19, 40) },
    { id: "s3", taskId: "classroom-linkedin", subjectId: "career", minutes: 28, completedMinutes: 28, focusQuality: 5, felt: "Easy", method: "visual", completedAt: day(-3, 16, 10) },
    { id: "s4", taskId: "classroom-dt-define", subjectId: "thinking", minutes: 20, completedMinutes: 20, focusQuality: 4, felt: "Okay", method: "visual", completedAt: day(-2, 16, 20) },
    { id: "s5", subjectId: "javascript", minutes: 18, completedMinutes: 18, focusQuality: 4, felt: "Okay", method: "practice", completedAt: day(-1, 15, 35) },
  ],
  concepts: [
    { id: "variables", subjectId: "javascript", name: "Variables", x: 20, y: 52, level: 4, confidence: 92, related: ["functions", "scope"], notes: "Comfortable with const and let." },
    { id: "functions", subjectId: "javascript", name: "Functions", x: 38, y: 27, level: 3, confidence: 78, related: ["variables", "scope", "arrays"], notes: "Practising callbacks." },
    { id: "arrays", subjectId: "javascript", name: "Arrays", x: 58, y: 46, level: 3, confidence: 72, related: ["functions", "objects", "async"], notes: "Map/filter are comfortable." },
    { id: "objects", subjectId: "javascript", name: "Objects", x: 78, y: 26, level: 2, confidence: 59, related: ["arrays", "apis"], notes: "Need more nested transformation practice." },
    { id: "scope", subjectId: "javascript", name: "Scope", x: 26, y: 78, level: 2, confidence: 61, related: ["variables", "functions", "async"], notes: "Revisit closure examples." },
    { id: "async", subjectId: "javascript", name: "Async", x: 56, y: 76, level: 1, confidence: 44, related: ["scope", "arrays", "apis", "react-state"], notes: "Promises still feel slippery." },
    { id: "apis", subjectId: "javascript", name: "APIs", x: 84, y: 68, level: 1, confidence: 38, related: ["objects", "async"], notes: "Think of request, response, error states." },
    { id: "react-state", subjectId: "frontend", name: "React state", x: 66, y: 12, level: 2, confidence: 65, related: ["async", "responsive-layout"], notes: "Derived state rule is clear." },
    { id: "responsive-layout", subjectId: "frontend", name: "Responsive layout", x: 43, y: 10, level: 3, confidence: 81, related: ["react-state"], notes: "Use intrinsic layout first." },
    { id: "affinity-mapping", subjectId: "thinking", name: "Affinity mapping", x: 12, y: 18, level: 3, confidence: 76, related: ["point-of-view", "how-might-we"], notes: "Group evidence by repeated needs before naming solutions." },
    { id: "point-of-view", subjectId: "thinking", name: "Point of View", x: 32, y: 32, level: 3, confidence: 79, related: ["affinity-mapping", "how-might-we"], notes: "Connect a learner, a need and the reason the need matters." },
    { id: "how-might-we", subjectId: "thinking", name: "How Might We", x: 52, y: 20, level: 2, confidence: 68, related: ["point-of-view", "bpmn"], notes: "Keep the question open enough for more than one idea." },
    { id: "bpmn", subjectId: "thinking", name: "BPMN process model", x: 70, y: 42, level: 2, confidence: 64, related: ["point-of-view", "usability-testing"], notes: "The current model should make the friction point visible before the solution appears." },
    { id: "usability-testing", subjectId: "thinking", name: "Usability testing", x: 82, y: 70, level: 1, confidence: 48, related: ["bpmn", "responsive-layout"], notes: "Observe what participants do, then ask what they expected." },
  ],
  mistakes: [
    {
      id: "mistake-box-model",
      subjectId: "frontend",
      topic: "CSS box model",
      whatWentWrong: "The card grew beyond its grid track on mobile.",
      originalThought: "Width included the padding automatically.",
      correction: "Content-box adds padding unless box-sizing is border-box.",
      insight: "Inspect the computed box before changing the grid.",
      stage: 3,
      createdAt: day(-8),
    },
    {
      id: "mistake-promises",
      subjectId: "javascript",
      topic: "Promise chains",
      whatWentWrong: "A rejected request skipped the expected UI update.",
      originalThought: "The final then block always runs.",
      correction: "A rejection jumps to the closest matching catch handler.",
      insight: "Draw the resolved and rejected paths as two lanes.",
      stage: 1,
      createdAt: day(-3),
    },
    {
      id: "mistake-leading",
      subjectId: "research",
      topic: "Interview questions",
      whatWentWrong: "The prompt suggested the answer I expected.",
      originalThought: "A concrete example would make the question easier.",
      correction: "Ask for a recent event first, then probe specifics.",
      insight: "Replace ‘Do you usually…’ with ‘Tell me about the last time…’",
      stage: 2,
      createdAt: day(-6),
    },
  ],
  ghostNotes: [
    { id: "g1", subjectId: "frontend", conceptId: "responsive-layout", message: "Future me: margin and padding are not the same thing. Inspect the box first.", createdAt: day(-8), surfacedAt: day(0) },
    { id: "g2", subjectId: "thinking", taskId: "classroom-dt-define", message: "Past you noticed that themes work better as needs, not feature ideas.", createdAt: day(-5) },
  ],
  journal: [
    { id: "j1", prompt: "What clicked today?", text: "Error states are part of the happy path, not an extra screen added at the end.", weather: "clear", subjectId: "frontend", tags: ["systems", "frontend"], createdAt: day(-3, 20) },
    { id: "j2", prompt: "What took more energy than expected?", text: "Naming the research themes. Tomorrow I’ll start with rough verbs before polished labels.", weather: "battery", subjectId: "research", tags: ["research"], createdAt: day(-1, 19) },
  ],
  assignments: [
    {
      id: "assignment-design-sprint",
      title: "Design Thinking Sprint Portfolio of Evidence",
      subjectId: "thinking",
      deadline: "2026-08-14T21:59:00.000Z",
      outcome: "A complete, personal record of the five sprint phases, the final presentation, honest assessment feedback, the Declaration of Authenticity and the signed logbook.",
      sections: [
        { id: "sprint-1", title: "Understand & Empathise", description: "Interview notes, observations, empathy maps and key learner insights.", estimate: 45, energy: 3, status: "done", blockers: "" },
        { id: "sprint-2", title: "Define", description: "Findings, themes, POV, problem statement, How Might We questions and an as-is BPMN model.", estimate: 75, energy: 4, status: "working", blockers: "Final source and layout check" },
        { id: "sprint-3", title: "Ideate", description: "Brainstorming, concept sketches, selection evidence and a to-be process model where useful.", estimate: 60, energy: 3, status: "not-started", blockers: "" },
        { id: "sprint-4", title: "Prototype", description: "Wireframes, mock-ups, main learner flow, mobile install guidance and a working prototype.", estimate: 70, energy: 4, status: "not-started", blockers: "Public mobile address still to be chosen" },
        { id: "sprint-5", title: "Test & Present", description: "Test plan, observations, participant feedback, recommendations and the final presentation.", estimate: 60, energy: 3, status: "not-started", blockers: "Needs consented test participants" },
        { id: "sprint-final", title: "Final PoE checks", description: "Assessment practices review, Declaration of Authenticity, completed logbook and working attachment links.", estimate: 45, energy: 2, status: "not-started", blockers: "Complete after the final presentation" },
      ],
    },
  ],
  notifications: [
    { id: "n1", title: "Networking comes first", message: "The LinkedIn task is due on 10 August. Want one small starting step?", read: false, createdAt: "2026-08-04T07:00:00.000Z" },
    { id: "n2", title: "The sprint hand-in is taking shape", message: "The logbook, final submission and SETA feedback share the 14 August deadline.", read: false, createdAt: "2026-08-04T08:00:00.000Z" },
    { id: "n3", title: "No hidden phase deadline", message: "The five phase submissions have no separate Classroom date, so they are grouped under the final sprint hand-in.", read: true, createdAt: "2026-08-03T15:00:00.000Z" },
  ],
  wellbeingCheckins: [],
  dna: [
    { id: "dna-short", label: "Short sessions", value: 88, evidence: "You finish 84% of sessions under 30 minutes.", confirmed: true },
    { id: "dna-visual", label: "Visual learning", value: 82, evidence: "Visual revision has your strongest completion rate." },
    { id: "dna-practice", label: "Practice", value: 76, evidence: "Practice sessions tend to receive higher focus ratings." },
    { id: "dna-explain", label: "Explaining", value: 64, evidence: "You return to concepts after teaching them aloud." },
    { id: "dna-afternoon", label: "Afternoon focus", value: 91, evidence: "Your strongest recent window was 15:20–16:10.", confirmed: true },
    { id: "dna-reading", label: "Reading", value: 48, evidence: "Long reading sessions are often shortened after 19:00." },
  ],
  freezeMode: false,
  currentWeather: "breezy",
};

seedDemoRecords(demoState);
